name: Generate Snake Animation

on:
  # Run automatically every 6 hours
  schedule:
    - cron: "0 */6 * * *"
  # Also allow running manually from the Actions tab
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # This step checks out a copy of your repository so the Action can access it
      - name: Checkout Repository
        uses: actions/checkout@v3

      # This step generates the snake animation SVG file
      - name: Generate Snake Animation
        uses: Platane/snk/svg-only@v3
        with:
          # Your GitHub username
          github_user_name: ${{ github.repository_owner }}
          
          # The output file for the SVG
          svg_out_path: dist/github-contribution-grid-snake.svg

      # This step pushes the generated SVG file back to your repository
      - name: Push Snake Animation to `output` Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          # The branch to push the generated file to
          target_branch: output
          # The directory containing the file to push
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
