# .github/workflows/main.yml
name: Generate Snake Animation

on:
  # Run automatically every 6 hours
  schedule:
    - cron: "0 */6 * * *"
  # Also allow running manually from the Actions tab
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate snake eating my contributions
        uses: Platane/snk/svg-only@v3
        with:
          # Your GitHub username is retrieved automatically
          github_user_name: ${{ github.repository_owner }}
          
          # The list of outputs to generate
          # This will create a file named `github-contribution-grid-snake.svg`
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push snake animation
        uses: crazy-max/ghaction-github-pages@v4
        with:
          # The branch to push the generated file to
          target_branch: output
          # The directory containing the file to push
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
